version: '3'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_APP=main.py
    volumes:
      - .:/app
