pipeline {
    agent any  // Runs on any available Jenkins agent

    triggers {
        pollSCM('* * * * *')  // Checks Git every minute for changes
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/INTRUDER1/jenkins-docker-project.git'
            }
        }

        stage('Build and Run Container') {
            steps {
                sh 'docker-compose up -d'
            }
        }

	
        stage('Run Ansible Playbook') {
            steps {
                sh 'ansible-playbook -i ansible-playbooks/inventory.ini ansible-playbooks/deploy.yml'
            }
        }

        stage('Test Application') {
            steps {
                sh 'curl -s http://localhost:5000'
            }
        }
    }
}

