---
- name: Deploy Flask App
  hosts: webserver
  become: yes
  tasks:
    - name: Install Python3 & Pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Copy application files
      copy:
        src: ../app/
        dest: /home/ubuntu/app/
    
    - name: Install dependencies
      pip:
        requirements: /home/ubuntu/app/requirements.txt
        executable: pip3

    - name: Run Flask Application
      shell: nohup python3 /home/ubuntu/app/main.py > app.log 2>&1 &

